
services:
  api:
    depends_on:
      - database
    build:
        context: .
    env_file:
      - .env
    ports:
      - 3000:3000

  database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
